CREATE TABLE G400ELCHE.MULAGT(   -- AGENTE
  AGTCOD NUMERIC(9,0) PRIMARY KEY DEFAULT 0 NOT NULL,
  AGTNOM CHAR(40) DEFAULT '' NOT NULL,
  AGTVPC CHAR(30) DEFAULT '' NOT NULL,
  AGTCGP NUMERIC(5,0) DEFAULT 0 NOT NULL,
  AGTMUN CHAR(20) DEFAULT '' NOT NULL,
  AGTPRV CHAR(30) DEFAULT '' NOT NULL
);

CREATE TABLE G400ELCHE.MULART(   -- ARTICULO
  ARTOID CHAR(32) PRIMARY KEY DEFAULT '' NOT NULL,
  ARTCOD NUMERIC(3,0) DEFAULT 0 NOT NULL,    
  ARTAPT CHAR(3) DEFAULT '' NOT NULL,         
  ARTOPC CHAR(3) DEFAULT '' NOT NULL,
  ARTRGM CHAR(3) DEFAULT '' NOT NULL,
  ARTIMP NUMERIC(13,2) DEFAULT 0 NOT NULL,
  ARTDES CHAR(300) DEFAULT '' NOT NULL
);

CREATE TABLE G400ELCHE.MULCDP(   -- CODIGO POSTAL
  CPCOD NUMERIC(5,0) PRIMARY KEY DEFAULT 0 NOT NULL,    
  CPPRV CHAR(20) DEFAULT '' NOT NULL,         
  CPMUN CHAR(30) DEFAULT '' NOT NULL          
);

CREATE TABLE G400ELCHE.MULART(   -- ARTICULO
  ARTOID CHAR(32) PRIMARY KEY DEFAULT '' NOT NULL,
  ARTCOD NUMERIC(3,0) DEFAULT 0 NOT NULL,    
  ARTAPT CHAR(3) DEFAULT '' NOT NULL,         
  ARTOPC CHAR(3) DEFAULT '' NOT NULL,
  ARTRGM CHAR(3) DEFAULT '' NOT NULL,
  AGTIMP NUMERIC(13,2) DEFAULT 0 NOT NULL,
  AGTDES CHAR(300) DEFAULT '' NOT NULL
);

CREATE TABLE G400ELCHE.MULINF(   -- INFRATOR
  INFNIF CHAR(9) PRIMARY KEY DEFAULT '' NOT NULL,
  INFTPN CHAR(10) DEFAULT '' NOT NULL,
  INFNOM CHAR(40) DEFAULT '' NOT NULL,
  INFTLF CHAR(20) DEFAULT '' NOT NULL,
  INFVPC CHAR(30) DEFAULT '' NOT NULL,
  INFCGP NUMERIC(5,0) DEFAULT 0 NOT NULL,
  INFMUN CHAR(20) DEFAULT '' NOT NULL,
  INFPRV CHAR(30) DEFAULT '' NOT NULL,
  INFFCP DATE DEFAULT '0001-01-01'
);

CREATE TABLE G400ELCHE.MULVHC( -- VEHICULO
	VHCMTC CHAR(10) PRIMARY KEY DEFAULT '' NOT NULL,
	VHCMRC CHAR(50) DEFAULT '' NOT NULL,
	VHCMDL CHAR(50) DEFAULT '' NOT NULL,
	VHCTPV CHAR(50) DEFAULT '' NOT NULL
);

CREATE TABLE G400ELCHE.MULVHC(   -- TIPO NIF
  INFNIF CHAR(9) PRIMARY KEY DEFAULT '' NOT NULL,
);

CREATE TABLE G400ELCHE.MULMUL(   -- MULTA
  MULOID CHAR(32) PRIMARY KEY DEFAULT '' NOT NULL,
  MULANO NUMERIC(4,0) DEFAULT 0 NOT NULL,
  MULFCH DATE DEFAULT '0001-01-01',
  MULIMP NUMERIC(13,2) DEFAULT 0 NOT NULL,
  MULOBS CHAR(100) DEFAULT '' NOT NULL,
  MULAGT NUMERIC(9,0) DEFAULT 0 NOT NULL, -- CUIDADO
  MULINF CHAR(9) DEFAULT '' NOT NULL, -- CUIDADO
  MULEST CHAR(50) DEFAULT '' NOT NULL,
  MULVH1 CHAR(10) DEFAULT '' NOT NULL,  -- CUIDADO
  MULVH2 CHAR(10) DEFAULT '' NOT NULL,  -- CUIDADO
  MULDSC NUMERIC(3,2) DEFAULT 0 NOT NULL,
  MULART CHAR(32) DEFAULT '' NOT NULL
);


CREATE TABLE G400ELCHE.MULART(   -- ARTICULO
  ARTOID CHAR(32) PRIMARY KEY DEFAULT '' NOT NULL,
  ARTCOD NUMERIC(3,0) DEFAULT 0 NOT NULL,    
  ARTAPT CHAR(3) DEFAULT '' NOT NULL,         
  ARTOPC CHAR(3) DEFAULT '' NOT NULL,
  ARTRGM CHAR(3) DEFAULT '' NOT NULL,
  ARTIMP NUMERIC(13,2) DEFAULT 0 NOT NULL,
  ARTDES CHAR(300) DEFAULT '' NOT NULL
);